// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroEmpleados.DAL;

#nullable disable

namespace RegistroEmpleados.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241018044010_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RegistroEmpleados.Models.Empleados", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NominaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoTrabajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("NominaId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("RegistroEmpleados.Models.Nominas", b =>
                {
                    b.Property<int>("NominaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AFP")
                        .HasColumnType("REAL");

                    b.Property<int>("HorasExtras")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ImpuestoSobreRenta")
                        .HasColumnType("REAL");

                    b.Property<double>("Prestamo")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarioNeto")
                        .HasColumnType("REAL");

                    b.Property<double>("SeguroMedico")
                        .HasColumnType("REAL");

                    b.HasKey("NominaId");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("RegistroEmpleados.Models.Empleados", b =>
                {
                    b.HasOne("RegistroEmpleados.Models.Nominas", "Nomina")
                        .WithMany()
                        .HasForeignKey("NominaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomina");
                });
#pragma warning restore 612, 618
        }
    }
}
